site_name: Variant Interpretation Pipeline
site_description: VIP is a flexible human variant interpretation pipeline for rare disease using state-of-the-art pathogenicity prediction (CAPICE) and template-based interactive reporting to facilitate decision support.
site_url: https://molgenis.github.io/vip/
repo_url: https://github.com/molgenis/vip/
edit_uri: edit/main/docs/
nav:
  - 'Home':
      - 'Introduction': 'index.md'
      - 'Key features': 'home/key_features.md'
  - 'Get Started':
      - 'Requirements': 'get_started/requirements.md'
      - 'Installation': 'get_started/installation.md'
      - 'Start running': 'get_started/start_running.md'
  - 'Usage':
      - 'Command-line options': 'usage/command-line-options.md'
      - 'Workflow': 'usage/workflow.md'
      - 'Input': 'usage/input.md'
      - 'Output': 'usage/output.md'
      - 'Config': 'usage/config.md'
  - 'Examples':
      - 'Nanopore': 'examples/nanopore.md'
      - 'Multi-project': 'examples/multi-project.md'
      - 'Reanalysis': 'examples/reanalysis.md'
  - 'Advanced':
      - 'Annotations': 'advanced/annotations.md'
      - 'Classification trees': 'advanced/classification_trees.md'
      - 'Report templates': 'advanced/report_templates.md'
  - 'Help':
      - 'Issues': 'help/issues.md'
      - 'Frequently asked questions': 'help/frequently_asked_questions.md'
  - 'About':
      - 'License': 'about/license.md'
      - 'Acknowledgements': 'about/acknowledgements.md'
markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search
  - mermaid2
  - panzoom
theme: readthedocs
strict: true
extra_css: [ custom.css ]
extra_javascript: [ js/mermaid.min.js ]
copyright: Copyright Â© 2026 University Medical Center Groningen All rights reserved
